/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MetricCard: typeof import('./components/MetricCard.vue')['default']
    MetricCard2: typeof import('./components/MetricCard2.vue')['default']
    MetricsCard: typeof import('./components/MetricsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeSeriesChart: typeof import('./components/TimeSeriesChart.vue')['default']
  }
}
